[project]
name = "llm-auto-update-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-ai>=0.0.31",
]

[tool.ruff]
fix = true
unsafe-fixes = true
line-length = 120

