name: "Generate Embeddings"
description: "Generate Embeddings for documentation in a git repository."

inputs:
  gemini-api-key:
    description: "The Gemini key to use Embeddings"
    required: true
  anthropic-api-key:
    description: "The Anthropic key to call claude models"
    required: true
  openai-api-key:
    description: "The OpenAI key to call openai models"
    required: true
  token:
    description: "The GitHub token to use for authentication."
    required: false
    default: ${{ github.token }}
  docs-path:
    description: "The path to where the docs are located in the repository. Relative to the root of the repository."
    required: true
  embeddings-action:
    description: "The action that generates the docs Embeddings"
    required: true
  source-change-pr:
    description: "The PR that triggered this action"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get latest workflow run ID
      id: get-run-id
      run: |
        RUN_ID=$(gh api repos/${{ github.repository }}/actions/workflows/${EMBEDDINGS_ACTION}/runs \
          --jq '.workflow_runs[] | select(.conclusion == "success") | .id' \
          | head -n 1)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        EMBEDDINGS_ACTION: ${{ inputs.embeddings-action }}

    - name: Fail if no run_id
      if: ${{ steps.get-run-id.outputs.run_id == '' }}
      run: |
        echo "No successful runs found for ${EMBEDDINGS_ACTION}"
        echo "try running ${EMBEDDINGS_ACTION} first"
        exit 1
      shell: bash
      env:
        EMBEDDINGS_ACTION: ${{ inputs.embeddings-action }}

    - name: Download artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: lapo-embeddings
        run-id: ${{ steps.get-run-id.outputs.run_id }}
        github-token: ${{ inputs.token }}
        path: faiss

    - name: "Checkout lapo docs Repository"
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        token: ${{ inputs.token }}
        repository: grafana/llm-auto-update-docs
        path: llm-auto-update-docs
        persist-credentials: false

    - name: move embeddings into .data/faiss
      run: |
        mkdir -p llm-auto-update-docs/.data/
        mv faiss llm-auto-update-docs/.data/
      shell: bash
    
    - name: Install uv
      uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1

    - name: Set up Python
      run: uv python install
      shell: bash
      working-directory: llm-auto-update-docs

    - name: Install dependencies
      run: uv sync
      shell: bash
      working-directory: llm-auto-update-docs

    - name: Run lapo docs
      run: |
        uv run lapo.py \
          --docs-path "${DOCS_PATH}" \
          --docs-repo "${DOCS_REPO}" \
          --source-change-pr "${SOURCE_CHANGE_PR}"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
        GITHUB_TOKEN: ${{ inputs.token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        DOCS_PATH: ${{ inputs.docs-path }}
        DOCS_REPO: ${{ github.repository }}
        SOURCE_CHANGE_PR: ${{ inputs.source-change-pr }}
      working-directory: llm-auto-update-docs
