name: Lapodocs

on:
  workflow_dispatch:
    inputs:
      pr-url:
        required: true
        default: https://github.com/grafana/grafana-plugin-examples/pull/482

jobs:
  lapodocs:
    name: Lapodocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/lapodocs
        with:
          pr-url: ${{ github.event.inputs.pr-url }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
